In [2]:
# word2vec - library name - "gensim"
#!pip install gensim

In [3]:
import gensim
from gensim.models import Word2Vec, KeyedVectors
import pandas as pd
import numpy as np

In [4]:
!pip install wget

  Preparing metadata (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9656 sha256=1d7c4def4bc190f6d350599695714a713a262eb878a5d437cc15388f9a60c160
  Stored in directory: /root/.cache/pip/wheels/8b/f1/7f/5c94f0a7a505ca1c81cd1d9208ae2064675d97582078e6c769
Successfully built wget


In [9]:
!mkdir -p ~/.kaggle

In [10]:
!cp kaggle.json ~/.kaggle/
!kaggle datasets download -d leadbest/googlenewsvectorsnegative300

Dataset URL: https://www.kaggle.com/datasets/leadbest/googlenewsvectorsnegative300
License(s): other
100% 3.17G/3.17G [03:23<00:00, 18.4MB/s]
100% 3.17G/3.17G [03:23<00:00, 16.7MB/s]


In [11]:
import zipfile
zip = zipfile.ZipFile('/content/googlenewsvectorsnegative300.zip')
zip.extractall('/content')
zip.close()

In [12]:
model = KeyedVectors.load_word2vec_format('/content/GoogleNews-vectors-negative300.bin',binary=True, limit=500000)

In [13]:
model['enjoy']

array([-1.25885010e-03, -4.83398438e-02, -2.83203125e-01,  3.24218750e-01,
        1.44653320e-02,  1.27929688e-01,  1.94335938e-01, -5.95703125e-02,
       -1.53320312e-01,  1.86523438e-01, -1.00097656e-01, -2.61718750e-01,
       -1.36718750e-02,  6.98242188e-02,  3.12500000e-02,  2.19726562e-01,
        1.60156250e-01,  1.64062500e-01,  2.85156250e-01, -4.24804688e-02,
       -1.42578125e-01,  1.91406250e-01,  8.98437500e-02,  1.82617188e-01,
        1.25976562e-01, -5.05371094e-02,  4.22363281e-02,  1.14257812e-01,
       -9.71679688e-02, -1.18652344e-01, -7.47070312e-02, -3.46679688e-02,
       -8.30078125e-02,  2.06054688e-01,  7.56835938e-02, -9.47265625e-02,
       -2.70996094e-02, -2.87109375e-01,  8.39843750e-02,  3.41796875e-01,
        6.44531250e-02,  2.39257812e-02,  1.47460938e-01,  1.66992188e-01,
       -1.04980469e-01, -2.73437500e-01, -1.26953125e-01,  6.29882812e-02,
        3.22265625e-02, -1.98974609e-02, -4.10156250e-02,  1.24023438e-01,
        1.68945312e-01,  

In [14]:
model['happy']

array([-5.18798828e-04,  1.60156250e-01,  1.60980225e-03,  2.53906250e-02,
        9.91210938e-02, -8.59375000e-02,  3.24218750e-01, -2.17285156e-02,
        1.34765625e-01,  1.10351562e-01, -1.04980469e-01, -2.90527344e-02,
       -2.38037109e-02, -4.02832031e-02, -3.68652344e-02,  2.32421875e-01,
        3.20312500e-01,  1.01074219e-01,  5.83496094e-02, -2.91824341e-04,
       -3.29589844e-02,  2.11914062e-01,  4.32128906e-02, -8.59375000e-02,
        2.81250000e-01, -1.78222656e-02,  3.79943848e-03, -1.71875000e-01,
        2.06054688e-01, -1.85546875e-01,  3.73535156e-02, -1.21459961e-02,
        2.04101562e-01, -3.80859375e-02,  3.61328125e-02, -8.15429688e-02,
        8.44726562e-02,  9.37500000e-02,  1.44531250e-01,  7.42187500e-02,
        2.51953125e-01, -7.91015625e-02,  8.69140625e-02,  1.58691406e-02,
        1.09375000e-01, -2.23632812e-01, -5.15747070e-03,  1.68945312e-01,
       -1.36718750e-01, -2.51464844e-02, -3.85742188e-02, -1.33056641e-02,
        1.38671875e-01,  

In [15]:
model['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [16]:
model.most_similar('happy')

[('glad', 0.7408890724182129),
 ('pleased', 0.6632170677185059),
 ('ecstatic', 0.6626912355422974),
 ('overjoyed', 0.6599286794662476),
 ('thrilled', 0.6514049172401428),
 ('satisfied', 0.6437949538230896),
 ('proud', 0.636042058467865),
 ('delighted', 0.627237856388092),
 ('disappointed', 0.6269949674606323),
 ('excited', 0.6247665286064148)]

In [17]:
model.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [18]:
model.most_similar('facebook')

[('Facebook', 0.7563533186912537),
 ('FaceBook', 0.7076998949050903),
 ('twitter', 0.6988552212715149),
 ('myspace', 0.6941817998886108),
 ('Twitter', 0.664244532585144),
 ('Facebook.com', 0.6529868245124817),
 ('FacebookFacebook', 0.6162722110748291),
 ('facebook.com', 0.6135972142219543),
 ('Twitter.com', 0.6102108359336853),
 ('TwitterTwitter', 0.6085205674171448)]

In [19]:
model.most_similar('Instagram')

[('Seesmic', 0.6571530699729919),
 ('Flickr', 0.6571183204650879),
 ('FacebookFacebook', 0.6347207427024841),
 ('Posterous', 0.6346837878227234),
 ('Tumblr', 0.6269142627716064),
 ('Friendfeed', 0.6202862858772278),
 ('Brightkite', 0.6198492646217346),
 ('FriendFeed', 0.5989659428596497),
 ('Del.icio.us', 0.5976784229278564),
 ('TwitterTwitter', 0.5914918184280396)]

In [28]:
model.most_similar('Rahul Gandhi')

KeyError: "Key 'Rahul Gandhi' not present in vocabulary"

In [20]:
model.similarity('happy','enjoy')

0.3910905

In [21]:
model.similarity('happy','cricket')

0.104148336

In [23]:
model.similarity('man','php')

0.008337109

In [24]:
vec = model['king'] - model['man'] + model['woman']

In [25]:
vec

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  

In [26]:
model.most_similar(vec)

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('queens', 0.5289887189865112),
 ('ruler', 0.5247419476509094)]

In [27]:
vec = model['India'] - model['INR'] + model['USA']
model.most_similar(vec)

[('USA', 0.7006986737251282),
 ('United_States', 0.4908815324306488),
 ('India', 0.4859938621520996),
 ('Canada', 0.4614386558532715),
 ('Great_Britain', 0.4597444236278534),
 ('Australia', 0.4297773838043213),
 ('America', 0.42488184571266174),
 ('United_Sates', 0.4182013273239136),
 ('Britain', 0.4124717116355896),
 ('United_Kingdom', 0.41157448291778564)]