In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'Text':['Learnbay teaches NLP', 'NLP is in Demand in market','We have to learn NLP'],
                   'Output':[1,0,1]})
df

Text  Output
0        Learnbay teaches NLP       1
1  NLP is in Demand in market       0
2        We have to learn NLP       1

# Bag of Words

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
cv1 = CountVectorizer(binary=True)

In [11]:
bow = cv.fit_transform(df['Text'])
bow1 = cv1.fit_transform(df['Text'])

In [5]:
# Vocab
print(cv.vocabulary_)

{'learnbay': 5, 'teaches': 8, 'nlp': 7, 'is': 3, 'in': 2, 'demand': 0, 'market': 6, 'we': 10, 'have': 1, 'to': 9, 'learn': 4}


In [6]:
print(bow[0].toarray())

[[0 0 0 0 0 1 0 1 1 0 0]]


In [7]:
print(bow[1].toarray())

[[1 0 2 1 0 0 1 1 0 0 0]]


In [8]:
print(bow[2].toarray())

[[0 1 0 0 1 0 0 1 0 1 1]]


In [9]:
bow.toarray()

array([[0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
       [1, 0, 2, 1, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1]], dtype=int64)

In [12]:
bow1.toarray()

array([[0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
       [1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1]], dtype=int64)

In [14]:
cv1.transform(["NLP is the leader in the market and we all have to learn it"]).toarray()

array([[0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1]], dtype=int64)